name: Daily Fantasy Sports Pipeline

# setting when this should run
on:
  schedule:
  - cron: '0 6 * * *'
  # allowing manual activation from website
  workflow_dispatch:

# what it should do
jobs:
  run-pipeline:
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas "snowflake-connector-python[pandas]" requests nba_api python-dotenv
      
      - name: Run NBA & NHL Data Pipelines
      # passing Snowflake credentials as hidden
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD}}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          # Running NBA ETL Pipeline
            python extract_nba.py
            python load_nba.py
            python transform_nba.py

          # Running NHL ELT Pipeline
            python extract_nhl.py
            python load_nhl.py
            python transform_nhl.py